version: '3'
services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    container_name: node
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/src"
    command: "npx nodemon -L src/server/server.js"


  mysql:
    image: mysql:5.7.31
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin

volumes:
  data:
